# -*- coding: utf-8 -*-

__author__ = 'bert'

"""
Api全局错误代码定义以及对应的说明

"""

SYSTEM_BUSY_CODE = -1
SUCCESS_CODE = 0
INVALID_ACCESS_TOKEN_CODE = 40001
ILLEGAL_ACCESS_TOKEN_CODE = 40002
ILLEGAL_OPENID_CODE = 40003
ILLEGAL_WOID_CODE = 40004
LACK_ACCESS_TOKEN_CODE = 40005
LACK_CALLBACK_URI = 40006
ACCESS_TOKEN_EXPIRED_CODE = 40007

#订单错误信息
PUT_ORDER_LOW_STOCKS = 71000
PUT_ORDER_PARAMETER_ERROR = 71001
GET_ORDER_PARAMETER_ERROR = 72000
GET_ORDER_REQUEST_ERROR = 72001
SUB_ORDER_STATUS_ERROR = 73000
CANCEL_ORDER_ERROR = 73001
GET_ORDER_LIST_ERROR = 74001
GET_EXPRESS_DETAILS_PARAMETER_ERROR = 75001

PAY_ORDER_STATUS_ERROR = 79000
PAY_ORDER_PARAMETER_ERROR = 79001

#系统自身错误信息
SYSTEM_ERROR_CODE = 995995
#查询商品详情的返回码
FAIL_GET_PRODUCT_DETAIL_CODE = 41001
FAIL_GET_PRODUCT_LIST_CODE = 41002

code2msg = {
	SYSTEM_BUSY_CODE : u'系统繁忙 ',
	SUCCESS_CODE : u'请求成功 ',
	INVALID_ACCESS_TOKEN_CODE : u'获取access_token无效',
	ILLEGAL_ACCESS_TOKEN_CODE : u'不合法的access_token',
	ILLEGAL_OPENID_CODE : u'不合法的openid',
	ILLEGAL_WOID_CODE : u'不合法的woid',
	LACK_ACCESS_TOKEN_CODE : u'缺少access_token参数',
	LACK_CALLBACK_URI : u'缺少callback_uri参数',
	ACCESS_TOKEN_EXPIRED_CODE : u'access_token过期',

	PUT_ORDER_LOW_STOCKS: u'创建订单请求中有商品库存不足',
	ORDER_PARAMETER_ERROR: u'创建订单请求参数错误或缺少参数',
	GET_ORDER_PARAMETER_ERROR: u'获取订单详情请求参数错误或缺少参数',
	GET_ORDER_REQUEST_ERROR: u'获取订单详情请求存在问题，请联系管理员',
	SUB_ORDER_STATUS_ERROR: u'有子订单的状态不是待发货,不能取消订单',
	CANCEL_ORDER_ERROR: u'取消订单修改订单状态失败',
	GET_ORDER_LIST_ERROR: u'获取订单列表存在问题',
	GET_EXPRESS_DETAILS_PARAMETER_ERROR: u'获取物流信息请求参数错误或缺少参数',
	PAY_ORDER_STATUS_ERROR: u'订单状态不正确,非待支付订单',
	PAY_ORDER_PARAMETER_ERROR: u'支付请求参数错误或缺少参数',

	SYSTEM_ERROR_CODE : u'系统自身异常',
	#查询商品详情的返回信息
	FAIL_GET_PRODUCT_DETAIL_CODE : u'查询商品详情失败，请联系管理员',
	FAIL_GET_PRODUCT_LIST_CODE : u'查询商品列表失败，请联系管理员',
}


